<a href="https://colab.research.google.com/github/ABBAS-37405/PYTHON-AND-DATA-SCIENCE/blob/main/PROJECT_BANK_CHURN_DATA_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

file_path = '/content/Bank+Churn+Data.xlsx'
df = pd.read_excel(file_path)

print(f"Successfully loaded '{file_path}' with {df.shape[0]} rows and {df.shape[1]} columns.")
display(df.head())

Successfully loaded '/content/Bank+Churn+Data.xlsx' with 500 rows and 13 columns.

,CustomerID,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Churn
0,1,Davis,764,Germany,Male,20,7,119274.87,3,1,0,107886.77,0
1,2,Smith,365,Spain,Female,64,3,203737.4,3,1,1,52848.11,0
2,3,Jones,519,Germany,Male,69,6,146780.5,3,0,0,94395.02,0
3,4,Jones,516,Germany,Female,59,0,23572.03,1,1,0,146739.55,0
4,5,Wilson,659,Spain,Female,21,2,7463.43,1,1,1,16036.55,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       500 non-null    int64
 1   Surname          500 non-null    object
 2   CreditScore      500 non-null    int64
 3   Geography        500 non-null    object
 4   Gender           500 non-null    object
 5   Age              500 non-null    int64
 6   Tenure           500 non-null    int64
 7   Balance          500 non-null    object
 8   NumOfProducts    500 non-null    int64
 9   HasCrCard        500 non-null    int64
 10  IsActiveMember   500 non-null    int64
 11  EstimatedSalary  497 non-null    float64
 12  Churn            500 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 50.9+ KB

In [4]:
# Clean 'Balance' column: remove non-numeric characters and convert to float
df['Balance'] = df['Balance'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
df['Balance'] = pd.to_numeric(df['Balance'], errors='coerce')

print("Data type of 'Balance' column after cleaning:")
display(df['Balance'].info())
print("First 5 rows of cleaned 'Balance' column:")
display(df['Balance'].head())

Data type of 'Balance' column after cleaning:
<class 'pandas.core.series.Series'>
RangeIndex: 500 entries, 0 to 499
Series name: Balance
Non-Null Count  Dtype
--------------  -----
499 non-null    float64
dtypes: float64(1)
memory usage: 4.0 KB

None

First 5 rows of cleaned 'Balance' column:

0    119274.87
1    203737.40
2    146780.50
3     23572.03
4      7463.43
Name: Balance, dtype: float64

In [5]:
missing_values = df.isnull().sum()
print("Missing values per column:")
display(missing_values[missing_values > 0])

Missing values per column:

Balance            1
EstimatedSalary    3
dtype: int64

In [7]:
mean_estimated_salary = df['EstimatedSalary'].mean()
df['EstimatedSalary'] = df['EstimatedSalary'].fillna(mean_estimated_salary)

print(f"Missing values in 'EstimatedSalary' after imputation: {df['EstimatedSalary'].isnull().sum()}")

Missing values in 'EstimatedSalary' after imputation: 0

In [8]:
print(f"Missing values in 'Balance' column: {df['Balance'].isnull().sum()}")

Missing values in 'Balance' column: 1

In [9]:
df.dropna(subset=['Balance'], inplace=True)

print(f"Missing values in 'Balance' column after dropping: {df['Balance'].isnull().sum()}")

Missing values in 'Balance' column after dropping: 0

In [10]:
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows in the DataFrame: {num_duplicates}")

if num_duplicates > 0:
    print("Displaying the first 5 duplicate rows:")
    display(df[df.duplicated()].head())

Number of duplicate rows in the DataFrame: 0

In [11]:
print('Current DataFrame Information:')
df.info()

Current DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
Index: 499 entries, 0 to 499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       499 non-null    int64
 1   Surname          499 non-null    object
 2   CreditScore      499 non-null    int64
 3   Geography        499 non-null    object
 4   Gender           499 non-null    object
 5   Age              499 non-null    int64
 6   Tenure           499 non-null    int64
 7   Balance          499 non-null    float64
 8   NumOfProducts    499 non-null    int64
 9   HasCrCard        499 non-null    int64
 10  IsActiveMember   499 non-null    int64
 11  EstimatedSalary  499 non-null    float64
 12  Churn            499 non-null    int64
dtypes: float64(2), int64(8), object(3)
memory usage: 54.6+ KB

In [12]:
average_credit_score_by_geography = df.groupby('Geography')['CreditScore'].mean()
print("Average Credit Score by Geography:")
display(average_credit_score_by_geography)

Average Credit Score by Geography:

Geography
France     592.549708
Germany    579.694268
Spain      601.871345
Name: CreditScore, dtype: float64

In [13]:
average_balance_by_gender_and_geography = df.groupby(['Geography', 'Gender'])['Balance'].mean()
print("Average Account Balance by Gender and Geography:")
display(average_balance_by_gender_and_geography)

Average Account Balance by Gender and Geography:

Geography  Gender
France     Female    129576.988542
           Male      133204.760133
Germany    Female    140888.278310
           Male      128591.024651
Spain      Female    120986.237473
           Male      119558.159125
Name: Balance, dtype: float64

In [14]:
cross_tab = pd.crosstab(df['HasCrCard'], df['IsActiveMember'])
print("Distribution of active members vs. non-active members according to having a credit card:")
display(cross_tab)

Distribution of active members vs. non-active members according to having a credit card:

IsActiveMember    0    1
HasCrCard
0               139  113
1               123  124

In [15]:
churn_by_products = df.groupby('NumOfProducts')['Churn'].value_counts().unstack(fill_value=0)
churn_by_products.columns = ['NoChurn', 'Churn']

churn_by_products['ChurnRate'] = (churn_by_products['Churn'] / (churn_by_products['NoChurn'] + churn_by_products['Churn'])) * 100

print("Customer Churn Rate per Number of Products Used:")
display(churn_by_products)

Customer Churn Rate per Number of Products Used:

               NoChurn  Churn  ChurnRate
NumOfProducts
1                   56     69  55.200000
2                   60     74  55.223881
3                   53     65  55.084746
4                   58     64  52.459016

In [16]:
average_credit_score_tenure_churn = df.groupby(['Tenure', 'Churn'])['CreditScore'].mean().unstack()
print("Average Credit Score by Tenure and Churn Status:")
display(average_credit_score_tenure_churn)

Average Credit Score by Tenure and Churn Status:

Churn            0           1
Tenure
0       615.307692  589.176471
1       591.000000  616.833333
2       618.590909  568.880000
3       541.625000  637.666667
4       606.086957  617.666667
5       625.200000  605.250000
6       540.263158  572.535714
7       595.764706  567.269231
8       590.800000  598.958333
9       562.550000  556.606061
10      632.827586  557.576923

In [17]:
average_salary_churned = df[df['Churn'] == 1]['EstimatedSalary'].mean()
print(f"Average Estimated Salary for Churned Customers: {average_salary_churned:.2f}")

Average Estimated Salary for Churned Customers: 83428.09